apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-deploy
  minReplicas: 2 # 최소 2개파드 
  maxReplicas: 7 # 최대 7개 파드
  targetCPUUtilizationPercentage: 90
